{{- if .Values.jira.web.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "jira.fullname" . }}-jira-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "jira.fullname" . }}-web
  minReplicas: {{ .Values.jira.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.jira.web.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.jira.web.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
