{{- if .Values.sentry.web.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-web
  minReplicas: {{ .Values.sentry.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.web.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.sentry.web.autoscaling.targetCPUUtilizationPercentage }}
  metrics:
    {{- if .Values.sentry.web.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sentry.web.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sentry.web.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sentry.web.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
